### ISSUE TITLE
I cannot install node-telegram-bot-api due to unreachable has-property-descriptors.

### ISSUE THREAD

**Issue by foxtrotdev** [inspect-js/has-property-descriptors#2]
I get such error message when I call `npm i node-telegram-bot-api`.

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://repo.huaweicloud.com/repository/npm/has-property-descriptors
npm ERR! 404 
npm ERR! 404  'has-property-descriptors@^1.0.0' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

More info here: https://github.com/yagop/node-telegram-bot-api/issues/964\

Question: is it possible that the changes have been to early so it points still to Huawei repo?

**Comment by ljharb** [comment]
I just published this package like an hour ago. If you’re using “not the real registry” (like huawei cloud, for ex ample) perhaps it takes time to update from the real one?

Report things present on npm but missing on your registry directly to your unofficial registry please, not to individual projects.
